export interface Review {
  name: string;
  when: string;
  text: string;
}

/**
 * Google reviews for the Ricky Wraps listing. GENERATED by scripts/fetch-reviews.mjs
 * from the Places API, do not hand-edit the numbers: run the script to refresh.
 * Review text is verbatim (whitespace normalised). Names are first name and last initial.
 */
export const REVIEWS = {
  heading: "What customers say",
  rating: 4.6,
  count: 68,
  asOf: "September 8, 2026",
  url: "https://maps.google.com/?cid=7698645542302137521",
  items: [
    {"name":"Fadi A.","when":"November 2025","text":"Great service and fast turnaround time. Highly recommended!"},
    {"name":"Steve G.","when":"July 2024","text":"RickyWraps put a black vinal wrap on my new Cadillac Lyriq. Fantastic look. He is a professional at what he does and how he handles customers. Great staff of employees too."},
    {"name":"Donielle H.","when":"March 2023","text":"Everyone was very professional and welcoming. They explained all the different options of tint. They did a very good job definitely would recommend."},
    {"name":"Ali J.","when":"November 2021","text":"I had an amazing experience with Ricky & the rest of the guys here! I came in to get my windows/windshield tinted as well as getting the top half of my vehicle wrapped. They exceeded my expectations beyond belief! Gave me a next day appointment, a great discount since I was getting a lot done, as well as being very professional throughout the whole process! When I got home, I noticed a small imperfection in the work & they stayed true to their word & told me to come back in so they can correct it! I definitely recommend anyone to come here, I’ve already referred a couple of my friends and family members to come here!"},
    {"name":"Kimonike T.","when":"October 2021","text":"This was a wonderful experience. He was very professional and let me know every detail through the process. I would recommend him to friend if they were looking to get some work done."},
  ] as Review[],
} as const;
